In [11]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [12]:
list=[1,2,3,4]
np_arr=np.array(list)
np_arr

array([1, 2, 3, 4])

In [24]:
lista = [1, 2, 3]
lista2 = [3, 2, 1]

In [25]:
n = np.array([lista, lista2])
print(n)


[[1 2 3]
 [3 2 1]]


In [27]:
n.shape

(2, 3)

In [28]:
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
np.empty(5)

array([2.12199579e-314, 7.63918485e-312, 5.79044937e-321, 7.63918485e-312,
       0.00000000e+000])

In [33]:
np.arange(5,23)
arr1=np.array([[1,2,3,4],[8,9,10,11]])
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [57]:
# Slice elements from index 1 to index 4 (exclusive)
print(arr[1:5])


[10 10 10]


In [42]:
arr[0:5] = 10
arr

array([10, 10, 10, 10])

In [54]:
slice_of_arr = arr[0:6]
slice_of_arr 

array([10, 10, 10, 10])

In [44]:
arr_copy = arr.copy()
arr_copy

array([10, 10, 10, 10])

In [52]:
arr_2d = np.array([[1,3,5],[3,5,1],[3,2,1]])
arr_2d 

array([[1, 3, 5],
       [3, 5, 1],
       [3, 2, 1]])

In [58]:
arr_2d[1]


array([3, 5, 1])

In [59]:
arr_2d[:2,1:]

array([[3, 5],
       [5, 1]])

In [60]:
arr_2d[:,1]

array([3, 5, 2])

In [62]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [64]:
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [65]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [66]:
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [68]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [69]:
obj = Series ([3,6,9,12])
obj

0     3
1     6
2     9
3    12
dtype: int64

In [70]:
obj.values

array([ 3,  6,  9, 12], dtype=int64)

In [71]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [77]:
countries = ['China','Germain','Japan','USA','USSR','Argentina']
countries

['China', 'Germain', 'Japan', 'USA', 'USSR', 'Argentina']

In [86]:

# Create a dictionary containing the data
ww2_dict = {'China': 'Allies', 'Germain': 'Axis', 'Japan': 'Axis', 'USA': 'Allies', 'USSR': 'Allies', 'Argentina': 'Allies'}

# Define the countries list
countries = ['China', 'Germain', 'Japan', 'USA', 'USSR', 'Argentina']

# Create a Series object using the data from ww2_dict and specifying the index as countries
obj2 = pd.Series(ww2_dict, index=countries)

print(obj2)


China        Allies
Germain        Axis
Japan          Axis
USA          Allies
USSR         Allies
Argentina    Allies
dtype: object


In [87]:
pd.isnull(obj2)

China        False
Germain      False
Japan        False
USA          False
USSR         False
Argentina    False
dtype: bool

In [93]:
obj2.name = "WW 2 casualties"
obj2

China        Allies
Germain        Axis
Japan          Axis
USA          Allies
USSR         Allies
Argentina    Allies
Name: WW 2 casualties, dtype: object

In [95]:
obj2.index.name="countries"
obj2

countries
China        Allies
Germain        Axis
Japan          Axis
USA          Allies
USSR         Allies
Argentina    Allies
Name: WW 2 casualties, dtype: object

In [97]:
my_ser = Series([1,2,3,4], index=['A','B','C','D'])
my_ser

A    1
B    2
C    3
D    4
dtype: int64

In [98]:
my_index = my_ser.index
my_index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [99]:
my_index[2:]

Index(['C', 'D'], dtype='object')

In [102]:
ser_2 = my_ser.reindex(['A','B','C','D','E','F'])
ser_2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [141]:
ser_2.reindex(['A','B','C','D','E','F','G'],fill_value=0)
ser_3 = Series(['USA','Mexico','Canada'],index=[0,3,10])
ser_3

0        USA
3     Mexico
10    Canada
dtype: object

In [142]:
ser_3.reindex(range(15),method='ffill')

0        USA
1        USA
2        USA
3     Mexico
4     Mexico
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14    Canada
dtype: object

In [112]:
# Create a DataFrame with random numbers
dframe = pd.DataFrame(np.random.randn(25).reshape((5,5)), index=['A','B','D','E','F'], columns=['col1','col2','col3','col4','col5'])

# Print the DataFrame
dframe


col1      col2      col3      col4      col5
A  0.535714 -0.821811 -1.506706  1.769900  0.785806
B  0.551149  1.276370 -0.804065  1.028618 -0.757011
D -0.603195  1.001072  0.843948 -0.266817 -0.711135
E -0.881889  0.338534  0.874096  0.426938  1.455454
F -0.904507  1.142065 -0.808603  0.146420  1.309232

In [113]:
dframe2 = dframe.reindex(['A','B','C','D','E','F'])
dframe2

col1      col2      col3      col4      col5
A  0.535714 -0.821811 -1.506706  1.769900  0.785806
B  0.551149  1.276370 -0.804065  1.028618 -0.757011
C       NaN       NaN       NaN       NaN       NaN
D -0.603195  1.001072  0.843948 -0.266817 -0.711135
E -0.881889  0.338534  0.874096  0.426938  1.455454
F -0.904507  1.142065 -0.808603  0.146420  1.309232

In [120]:
data = {
    'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc']
}
df = pd.DataFrame(data)
df

Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [127]:
address = ['Delhi', 'Bangalore', 'Chennai', 'Patna']
df['Address'] = address
df

Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna

In [129]:
data = {
    'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc']
}

In [132]:
df = pd.DataFrame(data)
df

Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc

In [134]:
df.insert(2, "Age", [21, 23, 24, 21], True)
df

Name  Height  Age  Age Qualification
0     Jai     5.1   21   21           Msc
1  Princi     6.2   23   23            MA
2  Gaurav     5.1   24   24           Msc
3    Anuj     5.2   21   21           Msc

In [135]:
new_columns = ['col1','col2','col3','col4','col5','col6']
dframe2.reindex(columns=new_columns)

col1      col2      col3      col4      col5  col6
A  0.535714 -0.821811 -1.506706  1.769900  0.785806   NaN
B  0.551149  1.276370 -0.804065  1.028618 -0.757011   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D -0.603195  1.001072  0.843948 -0.266817 -0.711135   NaN
E -0.881889  0.338534  0.874096  0.426938  1.455454   NaN
F -0.904507  1.142065 -0.808603  0.146420  1.309232   NaN

In [138]:
dframe1 = DataFrame(np.arange(9).reshape((3,3)),index=['SF','LA','NY'],columns=['pop','size','year'])
dframe1

pop  size  year
SF    0     1     2
LA    3     4     5
NY    6     7     8

In [140]:
dframe1.drop('LA')
dframe1.drop('year',axis=1)
dframe 

col1      col2      col3      col4      col5
A  0.535714 -0.821811 -1.506706  1.769900  0.785806
B  0.551149  1.276370 -0.804065  1.028618 -0.757011
D -0.603195  1.001072  0.843948 -0.266817 -0.711135
E -0.881889  0.338534  0.874096  0.426938  1.455454
F -0.904507  1.142065 -0.808603  0.146420  1.309232

# Differences between DataFrame and Series

In [ ]:
DataFrame can have multiple columns,
DataFrame can store more complex and heterogeneous data,
DataFrame can have different data types for each column,
DataFrame can handle mixed data types, such as numbers, strings, booleans, or dates,
DataFrames are designed for handling structured, tabular data with multiple variables
andas DataFrame is a 2D size-mutable, potentially heterogeneous tabular data structure with labelled axes (rows and columns). It is aligned in a tabular fashion in rows and columns.
Pandas DataFrame consists of three principal components, the data, rows, and columns. 

In [158]:
data = {
    'Name': ['Ali', 'Ahmed', 'Sara'],
    'Age': [25, 30, 28],
    'Gender': ['Male', 'Male', 'Female']
    }
df = pd.DataFrame(data)
print("DataFrame:")
print(df)
print(df.dtypes)

DataFrame:
    Name  Age  Gender
0    Ali   25    Male
1  Ahmed   30    Male
2   Sara   28  Female
Name      object
Age        int64
Gender    object
dtype: object


In [ ]:
while a Series can only have one.
while a Series can store more simple and homogeneous data.  
Series can only have one data type for the whole array. 
Series can only handle one data type at a time
while Series are more suited for representing and manipulating single columns of data
Pandas Series is a 1D labelled array capable of holding data of any type (integer, string, float, python objects, etc.).
The axis labels are collectively called index. It is like a column in excel.

In [144]:
ages = pd.Series([25, 30, 28])
print("\nSeries:")
print(ages)


Series:
0    25
1    30
2    28
dtype: int64


In [150]:
data = [1000, 3000, 4000, 5000]
s = pd.Series(data)
print(s)

0    1000
1    3000
2    4000
3    5000
dtype: int64


In [153]:
data = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
print(data)

a    1
b    2
c    3
d    4
dtype: int64


In [159]:
import pandas  
##### INTIALIZATION #####  
#STRING SERIES  
fruits = pandas.Series(["apples", "oranges", "bananas"])  
print("Fruit series:")  
print(fruits)  
#FLOAT SERIES  
temperature = pandas.Series([32.6, 34.1, 28.0, 35.9])  
print("\nTemperature series:")  
print(temperature)  
#INTEGER SERIES  
factors_of_12 = pandas.Series([1,2,4,6,12])  
print("\nFactors of 12 series:")  
print(factors_of_12)  
print("Type of this data structure is:", type(factors_of_12)) 

Fruit series:
0     apples
1    oranges
2    bananas
dtype: object

Temperature series:
0    32.6
1    34.1
2    28.0
3    35.9
dtype: float64

Factors of 12 series:
0     1
1     2
2     4
3     6
4    12
dtype: int64
Type of this data structure is: <class 'pandas.core.series.Series'>


In [160]:
import pandas 
# Integer indices 
fruits = pandas.Series(["apples", "oranges", "bananas"], index=[4, 3, 2]) 
print("Fruit series:") 
print(fruits) 
# String indices 
temperature = pandas.Series([32.6, 34.1, 28.0, 35.9], index=["one", "two", "three", "four"]) 
print("\nTemperature series:") 
print(temperature) 
# Non-unique index values 
factors_of_12 = pandas.Series([1,2,4,6,12], index=[1, 1, 2, 2, 3]) 
print("\nFactors of 12 series:") 
print(factors_of_12) 
print("Type of this data structure is:", type(factors_of_12)) 

Fruit series:
4     apples
3    oranges
2    bananas
dtype: object

Temperature series:
one      32.6
two      34.1
three    28.0
four     35.9
dtype: float64

Factors of 12 series:
1     1
1     2
2     4
2     6
3    12
dtype: int64
Type of this data structure is: <class 'pandas.core.series.Series'>


In [161]:
import numpy as np

# Creating a 2x3 matrix using a nested list
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix:")
print(matrix)

Matrix:
[[1 2 3]
 [4 5 6]]


In [163]:
import numpy as np

# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)


Array: [1 2 3 4 5]
