# NumPy Operations

In [3]:
import numpy as np

### Create a 1D array

In [4]:
arr =np.array([1,2,3,4])
print("1D Array:", arr)

1D Array: [1 2 3 4]


### Convert a list to a NumPy array

In [6]:
list1 = [1,2,3,4]
np_arr = np.array(list1)
print("Converted Array:", np_arr)

Converted Array: [1 2 3 4]


# Create a 2D array

In [11]:
lista = [1, 2, 3]
lista2 = [3, 2, 1]
n = np.array([lista, lista2])
print("2D Array:", n)


2D Array: [[1 2 3]
 [3 2 1]]


In [12]:
print("Shape of 2D Array:", n.shape)

Shape of 2D Array: (2, 3)


# Array Initialization Functions

In [13]:
print("Array of Zeros:", np.zeros(4))

Array of Zeros: [0. 0. 0. 0.]


In [14]:
print("Array of Ones (5x5):", np.ones([5,5]))

Array of Ones (5x5): [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
print("Empty Array:", np.empty(5))

Empty Array: [6.23042070e-307 4.67296746e-307 1.69121096e-306 1.29061074e-306
 5.94313193e+247]


In [16]:
print("Array using arange(5,23):", np.arange(5,23))

Array using arange(5,23): [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


# Array Slicing and Manipulation

In [87]:

arr1 = np.array([[1,2,3,4],[8,9,10,11]])
print("Original 2D Array:", arr1)

Original 2D Array: [[ 1  2  3  4]
 [ 8  9 10 11]]


In [18]:
print("Slice of 1D Array:", arr[1:5])


Slice of 1D Array: [2 3 4]


In [24]:
arr[0:5] = 10
print("Modified Array:", arr)

Modified Array: [10 10 10 10]


In [25]:
slice_of_arr = arr[0:6]
print("Slice of Modified Array:", slice_of_arr)

Slice of Modified Array: [10 10 10 10]


In [27]:
arr_copy = arr.copy()
print("Copy of Array:", arr_copy)

Copy of Array: [10 10 10 10]


In [29]:
arr_2d = np.array([[1,3,5],[3,5,1],[3,2,1]])
print("Original 2D Array:", arr_2d)

Original 2D Array: [[1 3 5]
 [3 5 1]
 [3 2 1]]


In [30]:
print("Slice of 2D Array:", arr_2d[1])

Slice of 2D Array: [3 5 1]


In [31]:
print("Slicing Rows and Columns:")
print(arr_2d[:2,1:])

Slicing Rows and Columns:
[[3 5]
 [5 1]]


In [32]:
print(arr_2d[:,1])

[3 5 2]


# Matrix Operations

In [39]:
arr2d = np.zeros((10,10))
print("2D Array of Zeros (10x10):", arr2d)

2D Array of Zeros (10x10): [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [41]:
arr = np.arange(50).reshape((10,5))
print("2D Array of Range (10x5):", arr)

2D Array of Range (10x5): [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [44]:
print("Transpose of Array:")
print(arr.T)

Transpose of Array:
[[ 0  5 10 15 20 25 30 35 40 45]
 [ 1  6 11 16 21 26 31 36 41 46]
 [ 2  7 12 17 22 27 32 37 42 47]
 [ 3  8 13 18 23 28 33 38 43 48]
 [ 4  9 14 19 24 29 34 39 44 49]]


In [43]:
print("Dot Product of Transpose and Original Array:")
print(np.dot(arr.T,arr))

Dot Product of Transpose and Original Array:
[[7125 7350 7575 7800 8025]
 [7350 7585 7820 8055 8290]
 [7575 7820 8065 8310 8555]
 [7800 8055 8310 8565 8820]
 [8025 8290 8555 8820 9085]]


# Pandas Operations

In [45]:
import pandas as pd
from pandas import Series, DataFrame

### Creating and Manipulating Series

In [49]:
obj = Series([3,6,9,12])
print("Series Object:", obj)

Series Object: 0     3
1     6
2     9
3    12
dtype: int64


In [50]:
print("Values in Series:", obj.values)

Values in Series: [ 3  6  9 12]


In [51]:
print("Index of Series:", obj.index)

Index of Series: RangeIndex(start=0, stop=4, step=1)


### Reindexing Series

In [52]:
my_ser = Series([1,2,3,4], index=['A','B','C','D'])
print("Original Series:", my_ser)

Original Series: A    1
B    2
C    3
D    4
dtype: int64


In [55]:
my_index = my_ser.index
print("Index of Series:", my_index)

Index of Series: Index(['A', 'B', 'C', 'D'], dtype='object')


In [56]:
print("Sliced Index:", my_index[2:])

Sliced Index: Index(['C', 'D'], dtype='object')


In [60]:
ser_2 = my_ser.reindex(['A','B','C','D','E','F'])
print("Reindexed Series with new Index:", ser_2)
print("Reindexed Series with fill value:", ser_2.reindex(['A','B','C','D','E','F','G'], fill_value=0))

Reindexed Series with new Index: A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64
Reindexed Series with fill value: A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
G    0.0
dtype: float64


In [ ]:
ser_3 = Series(['USA','Mexico','Canada'], index=[0,3,10])
print("Series with Gaps Filled Using Forward Fill:")
print(ser_3.reindex(range(15), method='ffill'))

### Creating and Manipulating DataFrames

In [65]:
data = {
    'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
    'Height': [5.1, 6.2, 5.1, 5.2],
    'Qualification': ['Msc', 'MA', 'Msc', 'Msc']
}

In [66]:
df = pd.DataFrame(data)

In [67]:
print("DataFrame:")
print(df)

DataFrame:
     Name  Height Qualification
0     Jai     5.1           Msc
1  Princi     6.2            MA
2  Gaurav     5.1           Msc
3    Anuj     5.2           Msc


# Adding a new column to DataFrame

In [71]:
address = ['Delhi', 'Bangalore', 'Chennai', 'Patna']
df['Address'] = address


In [72]:
print("DataFrame with New Column 'Address':")
print(df)

DataFrame with New Column 'Address':
     Name  Height Qualification    Address
0     Jai     5.1           Msc      Delhi
1  Princi     6.2            MA  Bangalore
2  Gaurav     5.1           Msc    Chennai
3    Anuj     5.2           Msc      Patna


# Inserting a new column at specific position

In [75]:
df.insert(2, "Age", [21, 23, 24, 21], True)

In [80]:
print("DataFrame with Age Inserted:")
print(df)

DataFrame with Age Inserted:
     Name  Height  Age  Age Qualification    Address
0     Jai     5.1   21   21           Msc      Delhi
1  Princi     6.2   23   23            MA  Bangalore
2  Gaurav     5.1   24   24           Msc    Chennai
3    Anuj     5.2   21   21           Msc      Patna


# Dropping rows and columns from DataFrame

In [84]:
print("DataFrame After Dropping 'LA':")
print(dframe1.drop('LA'))

DataFrame After Dropping 'LA':


NameError: name 'dframe1' is not defined

In [85]:
print("DataFrame After Dropping 'year' column:")
print(dframe1.drop('year', axis=1))

DataFrame After Dropping 'year' column:


NameError: name 'dframe1' is not defined

In [88]:
# Creating a Python list
my_list = [10, 'hello', 3.14, True]
print(my_list)


[10, 'hello', 3.14, True]


In [102]:
# Creating a Pandas Series
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(s)


a    10
b    20
c    30
d    40
dtype: int64
